services:
  hackathon_db:
    container_name: hackathon_db
    image: postgres:14
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}'" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    volumes:
      - /srv/data/hackathon/db:/var/lib/postgresql/data
    env_file:
      - .env.db
    networks:
      - hackathon-network
    restart: unless-stopped

  hackathon_pgadmin:
    container_name: hackathon_pgadmin
    image: dpage/pgadmin4
    depends_on:
      hackathon_db:
        condition: service_started
    healthcheck:
      test: [ "CMD", "wget", "-O", "-", "http://localhost:80/misc/ping" ]
    ports:
      - "8080:80"
    volumes:
      - /srv/data/hackathon/pgadmin/servers.json:/pgadmin4/servers.json
    env_file:
      - .env.pgadmin
    networks:
      - hackathon-network
    restart: unless-stopped

  hackathon_backend:
    container_name: hackathon_backend
    build: .
    depends_on:
      hackathon_db:
        condition: service_healthy
    ports:
      - "5000:5000"
    volumes:
      - ./upload:/usr/src/app/upload
    env_file:
      - .env.backend
    networks:
      - hackathon-network
    restart: unless-stopped

networks:
  hackathon-network:
