services:
  hackathon_postgres:
    container_name: hackathon_postgres
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - /srv/data/hackathon/db:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - hackathon-network
    restart: unless-stopped

  hackathon_pgadmin:
    links:
      - hackathon_postgres:postgres
    container_name: hackathon_pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /srv/data/hackathon/pgadmin/servers.json:/pgadmin4/servers.json
    env_file:
      - docker.env
    networks:
      - hackathon-network
    restart: unless-stopped

  hackathon_backend:
    links:
      - hackathon_postgres:postgres
    container_name: hackathon_backend
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./upload:/usr/src/app/upload
    env_file:
      - docker.env
    networks:
      - hackathon-network
    restart: unless-stopped

networks:
  hackathon-network:
