version: "3"
services:
  hackathon_postgres:
    container_name: hackathon_postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - /data/postgres:/data/postgres
    env_file:
    - docker.env
  
  hackathon_pgadmin:
    links:
    - postgres:postgres
    container_name: hackathon_pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - /data/pgadmin:/root/.pgadmin
    env_file:
    - docker.env
