version: "3"
services:
  hackathon2021_postgres:
    container_name: hackathon_postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - hackathon2021-network
    restart: on-failure
    
  hackathon2021_pgadmin:
    links:
      - hackathon2021_postgres:postgres
    container_name: hackathon_pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - hackathon2021-network
    restart: on-failure

  hackathon2021_backend:
    links:
      - hackathon2021_postgres:postgres
    container_name: hackathon_backend
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./upload:/usr/src/app/upload
    env_file:
      - docker.env
    networks:
      - hackathon2021-network

networks:
  hackathon2021-network:
